### ISSUE TITLE
Default to SHA512

### ISSUE THREAD

**Issue by Firesphere** [elliot-sawyer/totp-authenticator#7]
Instead of SHA1

**Comment by elliot-sawyer** [comment]
I considered this during the initial development, but it seems [Google Authenticator ignores the `algorithm` parameter if set in the QR code](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). I haven't actually tested that but if it does support SHA512 I would prefer to default to that!

**Comment by elliot-sawyer** [comment]
I had a go at updating this to SHA512 but it seems Google Authenticator and Authy don't support it:

- [TOTPProvider.php](https://github.com/elliot-sawyer/totp-authenticator/blob/master/src/Providers/TOTPProvider.php#L41)
- [TOTPAuthenticator.php](https://github.com/elliot-sawyer/totp-authenticator/blob/master/src/Authenticators/TOTPAuthenticator.php#L51)

If you set the first parameter of `new Totp()` to "sha512", a secret will still get generated but Google Authenticator will issue the wrong 6 digit codes. There are a few threads on the internet confirming the issue, but [there's a handy chart over here](https://github.com/eloquent/otis/wiki/otp-app-capabilities).

I think it's still a good idea to make the option configureable because there may be other implementations in use that do support it, that the dev may explicitly need to target and support. However, I'm intending to target the two most popular smartphone authenticators (Authenticator and Authy), so we'll have to default to sha1.

**Comment by elliot-sawyer** [comment]
We have to default to SHA1 to support Google Authenticator and Authy. [I've raised a PR to make it configurable to sha256 or sha512](https://github.com/elliot-sawyer/totp-authenticator/pull/10).
